#cloud-config

# Add groups to the system
# The following example adds the ubuntu group with members foo and bar and
# the group cloud-users.
coreos:
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

  etcd2:
    # multi-region and multi-cloud deployments need to use $public_ipv4
    proxy: "on"
    listen-client-urls: "http://0.0.0.0:2379"
    initial-cluster: "{{.env.etcd_initial_cluster}}"

